import type { DealInput } from '../types'

/** First scored mandate. Facts come from the Stage 2 card, not from the UI.
 *  The engine reads this. It does not read pre-baked scores.
 */
export const novatechCase: DealInput = {
  mandate: {
    company: 'NovaTech Solutions',
    sector: 'Healthtech',
    stage: 'Series B',
    ask: '₹350 Cr',
    raised: '₹60 Cr',
    assessed: '2026-07-30',
    hq: 'Mumbai, India',
  },
  memo: [
    "NovaTech is an India healthtech company selling care-management software to enterprises and insurers. The founder is a pharmacist from BITS Pilani with an IIM-K MBA, and the operating history is nine years.",
    "FY26 revenue is ₹27.2 Cr, up 83%. Contribution margin is 29%. Cash at year end was negative, which is the item that would stop a process. Existing investors are described as committing half the new round; that claim is not named.",
    "The ask is ₹350 Cr on ₹60 Cr already raised. The sector is large enough. The constraint is not the market. It is runway, a messy co-founder record, and an ask that is large against capital already in.",
  ],
  valuation: {
    raiseCr: { low: 50, high: 60 },
    rangeCr: { low: 350, high: 500 },
    dilutionPct: { low: 15, high: 20 },
    runwayAfterMonths: { low: 18, high: 24 },
    clock: {
      monthsLow: 5,
      monthsHigh: 7,
      phases: [
        {
          id: 'preparation',
          name: 'Preparation',
          weeks: 3,
          why: 'Settle cash and the open flags before outreach.',
        },
        {
          id: 'outreach',
          name: 'Outreach',
          weeks: 6,
          why: 'Open the process once the hole is gone.',
        },
        {
          id: 'meetings',
          name: 'Meetings',
          weeks: 4,
          why: 'Defend the range against the peer set.',
        },
      ],
    },
    medianMultiple: 21.8,
    multipleKind: 'EV/Revenue',
    peers: [
      {
        id: 'beato',
        name: 'BeatO',
        year: 2022,
        stage: 'Series B',
        revenueCr: 180,
        multiple: 18.4,
        source: 'Tracxn',
        why: 'Same chronic-care, India. Last raise before the re-rating.',
        fragility: 'Four years old. Drop it and the median moves.',
        journey: [
          {
            year: 2019,
            month: 3,
            stage: 'Seed',
            revenueCr: 4,
            raiseCr: 11.75,
            source: 'Entrackr',
          },
          {
            year: 2021,
            month: 6,
            stage: 'Series A',
            revenueCr: 25,
            source: 'Entrackr',
          },
          {
            year: 2022,
            month: 11,
            stage: 'Series B',
            revenueCr: 180,
            multiple: 18.4,
            raiseCr: 270,
            source: 'Tracxn',
          },
        ],
      },
      {
        id: 'pb-health',
        name: 'PB Health',
        year: 2025,
        stage: 'Seed',
        revenueCr: 42,
        multiple: 28.0,
        source: 'PitchBook',
        why: 'Closest model. Recent capital event with Fitterfly.',
        journey: [
          {
            year: 2025,
            month: 5,
            stage: 'Seed',
            revenueCr: 42,
            multiple: 28.0,
            raiseCr: 1900,
            source: 'PitchBook',
          },
        ],
      },
      {
        id: 'fitterfly',
        name: 'Fitterfly',
        year: 2023,
        stage: 'Series A',
        revenueCr: 95,
        multiple: 19.0,
        source: 'VCCEdge',
        why: 'Same clubbed sub-sector. Older multiple.',
        journey: [
          {
            year: 2022,
            month: 7,
            stage: 'Series A',
            revenueCr: 5,
            raiseCr: 100,
            source: 'Inc42',
          },
          {
            year: 2023,
            month: 6,
            stage: 'Series A',
            revenueCr: 95,
            multiple: 19.0,
            source: 'VCCEdge',
          },
        ],
      },
    ],
    raiseSentence:
      'Cash is nil, so the band has to plug the hole and still leave 18–24 months to the next print. Smaller leaves the process exposed. Larger takes dilution this profile cannot defend yet.',
    argument:
      'What this peer set can defend today on FY26 revenue. The median is generous because several prints predate the healthtech re-rating.',
    useOfFunds:
      'Stated uses are growth. Almost none goes to debt. Cash was nil at year end, so economically part of the round will plug working capital whatever the deck says.',
  },
  investors: {
    bookSentence:
      'One healthcare lead and two follows. Not a list of everyone who has ever written a healthtech cheque.',
    argument:
      'A healthcare specialist opens a ₹50–60 Cr Series B in chronic care. Generalists can write the same cheque. They will not underwrite clinical risk first on a 6.8 look with nil cash. Angels and most micro VCs cannot move this book. If the unnamed ₹30 Cr follow is real, new money drops. Until it is named, book the full raise.',
    types: [
      {
        id: 'healthcare-vc',
        name: 'Healthcare VCs',
        thesis: 'sector',
        checkCr: { low: 20, high: 40 },
        sentence: '₹20–40 Cr. They underwrite clinical risk.',
        why: 'India healthcare funds that write Series A and B. This company sells care-management software to enterprises and insurers. A generalist will diligence the clinical layer for months. A healthcare specialist already has the framework.',
        fragile:
          'Cash is nil. Some of these funds still take a first meeting. They will not term-sheet on this runway.',
        next: 'One of these writes ₹25–35 Cr and sets the terms. If we cannot get a healthcare lead, the book becomes a generalist lead and a slower clock.',
      },
      {
        id: 'series-b-generalist',
        name: 'Series B generalists',
        thesis: 'stage',
        checkCr: { low: 20, high: 40 },
        sentence: '₹20–40 Cr. They come in after a healthcare lead is in.',
        why: 'They can write the cheque. They do not want to be first on a healthtech story with a 6.8 look and nil cash.',
        fragile:
          'If cash settles and a healthcare name is in, they fill ₹15–20 Cr. Without that, they bounce.',
        next: 'Promote them to lead only if the healthcare book is empty. The clock gets longer.',
      },
      {
        id: 'family-office',
        name: 'Family offices',
        thesis: 'family',
        checkCr: { low: 5, high: 15 },
        sentence: '₹5–15 Cr. The last slice.',
        why: 'Cheques that close a book, not open it. Useful once a lead is in.',
        fragile:
          'They do not set terms. Building the process around them wastes the clock.',
        next: 'Keep them for ₹10–15 Cr at the end. Do not put them in the first two weeks of outreach.',
      },
      {
        id: 'existing',
        name: 'Existing investors',
        thesis: 'existing',
        checkCr: { low: 30, high: 30 },
        sentence: 'The deck claims ₹30 Cr. It does not name who.',
        why: 'If the follow is real, new money drops to ₹25–30 Cr and the book is easier.',
        fragile:
          'The score already flagged this. Half the ask treated as insider money with no names.',
        next: 'Get the letters. If the ₹30 Cr is new money, this row leaves the book.',
      },
      {
        id: 'angels',
        name: 'Angels',
        thesis: 'angel',
        checkCr: { low: 0.25, high: 2 },
        sentence: 'A ₹1 Cr cheque does not move this book.',
        why: 'Angels write ₹25 L to ₹2 Cr. Right for seed. Wrong for a ₹55 Cr Series B.',
        fragile: 'Founders still take these meetings because they are easy to get.',
        next: 'Do not spend the clock here. A personal cheque can still sit in the last slice if someone insists. It is not a type we build around.',
      },
      {
        id: 'micro-vc',
        name: 'Micro VCs',
        thesis: 'micro',
        checkCr: { low: 3, high: 8 },
        sentence: 'Typical ₹3–8 Cr. They lead seed. They cannot lead this.',
        why: 'India micro VCs write early cheques. A ₹8 Cr cheque is 15% of this raise. Not enough to open the process.',
        fragile:
          'They can take the last ₹5 Cr. The meeting cost is the same as a family office that writes more.',
        next: 'Skip them for outreach. If the raise were ₹8–15 Cr, this row would lead.',
      },
    ],
    fills: [
      {
        typeId: 'healthcare-vc',
        label: 'Healthcare lead',
        cr: { low: 25, high: 35 },
      },
      {
        typeId: 'series-b-generalist',
        label: 'Generalist follow',
        cr: { low: 15, high: 20 },
      },
      {
        typeId: 'family-office',
        label: 'Family and existing',
        cr: { low: 10, high: 15 },
      },
    ],
  },
  evidence: {
    "A.1.a": {
      band: "Excellent",
      reasoning: "Khushboo Aggarwal, the CEO and Founder, holds a Pharmacy (Hons.) degree from BITS Pilani and an MBA from IIM-K. Both institutions are considered top-tier in India, and her Pharmacy degree is directly relevant to the healthcare sector, satisfying the 'Excellent' criteria.",
      soWhat: "Strong founder education in a relevant domain from top-tier institutions provides a solid foundation for the company's strategic and operational leadership in healthtech.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "as at 2026-08-23",
      citations: [
        { source: "Project Orah Teaser_vff.pptx", quote: "Khushboo Aggarwal: Pharmacy (Hons.) BITS Pilani, MBA IIM-K.", locator: "slide 20", type: "Company Deck", tier: "Tier 2" },
        { source: "Web Research", quote: "Khushboo Aggarwal (Founder & CEO): Education: Pharmacy (Hons.) from BITS Pilani and an MBA from IIMK (IIM Kozhikode).", locator: "Batch 2, Q3 retrieved 2026-08-23", type: "Web Research", tier: "Tier 3" },
      ],
    },
    "A.1.b": {
      measured: { value: 8, unit: "Count" },
      reasoning: "Eight marquee logos are externally corroborated. Capped at 3 (the Excellent cut) because attribution specifically to the founder's network is inferred, not stated — supported by FY25–FY26 sales-team cost of only c.₹1.1 Cr, which implies founder-led origination. Confirm logo-by-logo in DD.",
      diligenceAsk: "Already at the top band on current evidence. Confirm the following in due diligence so the rating holds: Capped at 3 (the Excellent cut) because attribution specifically to the founder's network is inferred, not stated — supported by FY25–FY26 sales-team cost of only c.₹1.1 Cr, which implies founder-led origination.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      flag: {
        kind: "inferred",
        summary: "Eight logos against ₹1.1 Cr of sales. Origination is inferred, not shown.",
      },
      citations: [
        {
          source: "Startup Story Media — \"Zyla Health Raises $4 Million in Series A Funding\"",
          quote: "Already at the top band on current evidence. Confirm the following in due diligence so the rating holds: Capped at 3 (the Excellent cut) because attribution specifically to the founder's network is inferred, not stated — supported by FY25–FY26 sales-team cost of only c.₹1.1 Cr, which implies founder-led origination.",
          type: "Press",
          tier: "2",
          url: "https://startupstorymedia.com/insights-zyla-health-raises-4-million-in-series-a-funding-to-revolutionize-healthcare-delivery/",
        },
      ],
    },
    "A.1.c": {
      measured: { value: 9, unit: "Years" },
      reasoning: "GAP AND CONFLICT. Press at the Nov-2023 Series A names Tanmay Patil as co-founder; the July-2026 deck does not mention him and names Aishwary Bhashkar instead. Nine years is the company's age, not a verified co-founder tenure. If Bhashkar joined later the true figure could be materially lower. See Evidence & Workings D90 — must be confirmed.",
      diligenceAsk: "Already at the top band on current evidence. Confirm the following in due diligence so the rating holds: GAP AND CONFLICT.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      flag: {
        kind: "contradiction",
        summary: "Nov-2023 press names Tanmay Patil as co-founder. The July deck names Aishwary and omits Patil.",
      },
      citations: [
        {
          source: "Digital Health News — \"Healthtech Startup Zyla Raises $4Mn Series A\"",
          quote: "Already at the top band on current evidence. Confirm the following in due diligence so the rating holds: GAP AND CONFLICT.",
          type: "Press",
          tier: "2",
          url: "https://www.digitalhealthnews.com/healthtech-startup-zyla-raises-4mn-series-a-funding-led-by-exfinity-ventures",
        },
      ],
    },
    "A.1.d": {
      measured: { value: 10, unit: "Years" },
      reasoning: "Directly relevant healthcare experience across consulting and nine years operating Zyla. Comfortably above the 10-year Excellent cut.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "A.1.e": {
      band: "Fair",
      reasoning: "The CEO has no prior founding experience. The CTO founded MirrAR but its funding history and outcome are not documented anywhere in the material, so the Good anchor (\"reached institutional funding, whatever the outcome\") is not demonstrably met and the band below is taken, per the Qualitative Anchors instruction.",
      diligenceAsk: "Confirm the gap noted in diligence — The CTO founded MirrAR but its funding history and outcome are not documented anywhere in the material, so the Good anchor (\"reached institutional funding, whatever the outcome\") is not demonstrably met and the band below is taken, per the Qualitative Anchors instruction. — to verify whether this parameter should move from Fair (5.0) to Good (7.0).",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "Confirm the gap noted in diligence — The CTO founded MirrAR but its funding history and outcome are not documented anywhere in the material, so the Good anchor (\"reached institutional funding, whatever the outcome\") is not demonstrably met and the band below is taken, per the Qualitative Anchors instruction. — to verify whether this parameter should move from Fair (5.0) to Good (7.0).", type: "Company document", tier: "2" },
      ],
    },
    "A.2.a": {
      band: "Good",
      reasoning: "Full-time, credible, long in seat. Held back from Excellent because there is no evidence he has shipped and scaled a comparable product at the next stage of scale, and the deck gives no start date or product-scale metrics.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "A.2.b": {
      band: "Good",
      reasoning: "Two full-time commercial leaders, with the CBO bringing directly relevant healthcare-sector relationships. Not Excellent: no start dates, no evidence of a quota-carrying team through the next revenue band, and no confirmation that the founder has stopped closing the largest accounts.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "A.2.c": {
      band: "Fair",
      reasoning: "No CFO or finance head is named, and the company already carries institutional capital — which points to Poor. Held at Fair because the quarterly cost build in the model is of genuine MIS quality, implying real finance capability somewhere in the business. Confirm who owns the monthly close and the date of the last closed MIS.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "A.2.d": {
      band: "Good",
      reasoning: "Full-time operations leader with high-volume experience (Oyo, EXL). Not Excellent: no start date and no evidence he has run this function at several times current volume in a clinical setting.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "A.3.b": {
      measured: { value: 2, unit: "Count" },
      reasoning: "Two named advisors of genuine standing — one pharma operator, one HR/legal. Engagement cadence and terms are not disclosed.",
      diligenceAsk: "Confirm the gap noted in diligence — Engagement cadence and terms are not disclosed. — to verify whether this parameter should move from Good (7.0) to Excellent (9.0).",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "Confirm the gap noted in diligence — Engagement cadence and terms are not disclosed. — to verify whether this parameter should move from Good (7.0) to Excellent (9.0).", type: "Company document", tier: "2" },
      ],
    },
    "A.3.c": {
      measured: { value: 5, unit: "Count" },
      reasoning: "Five institutional names, well clear of the Excellent cut of 3. Corroborated by the lead investor's own disclosure (Tier 1).",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Exfinity Venture Partners — investor's own media page", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "B.1": {
      measured: { value: 27.24, unit: "INR Cr" },
      reasoning: "₹27.24 Cr FY26 actual — Fair band, and the binding constraint on the Financials category (the Series A Good cut is ₹40 Cr). POST-YEAR-END EVIDENCE THAT COULD MOVE THIS: the teaser's current-traction page reports 61 clients and 217,000+ lives against FY26's 51 clients and 212,940 lives, so part of the FY27 ramp to 81 clients is already delivered. Multiplying 217,000 lives by the quoted ₹2,106 average sponsored preventive-care spend gives ₹45.7 Cr, which sits between the FY26 actual and the FY27E plan of ₹55.04 Cr — but ₹2,106 is described as spend per life, not revenue per life, and it exceeds the plan's own FY27E ARPU of ₹1,790, so the two are not the same measure and it has NOT been used to score. Scored on the FY26 actual. ASK for monthly revenue for FY26 and Q1FY27: the model contains no quarterly revenue series at all, and if Q1FY27 is running at ₹11–12 Cr this row moves to Good. Workings and the cross-check at Evidence & Workings rows 45 and 71.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "B.2": {
      measured: { value: 82.9, unit: "%" },
      reasoning: "82.9% on operating revenue; 71.9% including other income. Good band either way. Note growth was 107% in FY24 and 78% in FY25 — it is not decelerating, which is unusual at this scale.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "B.3": {
      measured: { value: 32.5, unit: "%" },
      reasoning: "32.5% on the model's own CM1 line (after clinical and ops delivery cost). The deck's headline \"48.8% gross margin\" is the pre-labour figure and would score Good; CM1 is the honest delivery margin and scores Fair.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "B.4": {
      measured: { value: 28.6, unit: "%" },
      reasoning: "28.6%, Good band. Only ₹1.06 Cr of sales and marketing spend sits between CM1 and CM2 — 3.9% of revenue. That is the zero-CAC claim quantified.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "B.5": {
      measured: { value: -25.1, unit: "%" },
      reasoning: "-25.1%, which falls 0.1 points below the Fair cut of -25.0% and therefore bands as Poor. On the including-other-income denominator it is -24.3% and would band Fair. Genuinely knife-edge — do not over-read the Poor.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Poor (3.0) band holds, rather than moving to Fair (5.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "B.6": {
      measured: { value: -28.8, unit: "%" },
      reasoning: "-28.8%, Fair band. No tax charge — ₹32.4 Cr of carried-forward losses remain and shelter profits into FY30 on the plan.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "B.7": {
      measured: { value: 0, unit: "Months" },
      reasoning: "SINGLE LARGEST OPEN ITEM. Nil months on liquid cash — FY26 closing cash is negative ₹0.55 Cr against average net burn of ₹0.91 Cr per month. But M. BS row 11 carries ₹17.89 Cr of \"Investments\" held flat with no schedule; if that is liquid treasury, runway is c.19.7 months and this becomes Good. Confidence is Medium on the classification, High on the arithmetic. Resolve before any recommendation is acted on.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Poor (3.0) band holds, rather than moving to Fair (5.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      flag: {
        kind: "gap",
        summary: "FY26 closing cash is negative. Runway on liquid cash is nil.",
      },
    },
    "B.8": {
      measured: { value: 9.7, unit: "Days" },
      reasoning: "9.7 days, Excellent. Sponsor-funded B2B collections are fast. Watch the unexplained step down from 10 days to 5 days from FY31 in the plan.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Negative search result across Entrackr, Inc42, Digital Health News and Business Standard", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "B.9": {
      measured: { value: 4.9, unit: "%" },
      reasoning: "4.9%, Excellent. ₹1.33 Cr of borrowings at 12%, fully amortised by FY28. Leverage is not an issue here.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "C.1": {
      band: "Fair",
      reasoning: "Nine years as at 30-Jul-2026. The Series A ideal band is 2–6 years and the Fair tolerance runs to 9, so this lands exactly on the Fair boundary. The company's own timeline explains it: 2017–2023 was B2C validation, and B2B product-market fit was only reached from 2023. A nine-year-old company raising a ₹60 Cr Series A is a genuine flag — it means six years produced little scale.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Digital Health News — \"Healthtech Startup Zyla Raises $4Mn Series A\"", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "C.2": {
      measured: { value: 82.2, unit: "%" },
      reasoning: "82.2% from corporate and domestic-insurance contracts — Excellent band. But this is a revenue-line classification, not a contract read: no tenor, notice period or renewal term appears in the model. Corporate wellness budgets that re-tender annually are repeat, not recurring. Sight the five largest contracts.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Digital Health News — Series A coverage, quoting the founder", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "C.3.a": {
      band: "Good",
      reasoning: "Genuinely proprietary domain layer with clinician-in-the-loop validation on millions of interactions, and the core know-how is held in-house — that is the Good anchor. Not Excellent: no granted patent or registered IP is evidenced, and there is no evidence of enforcement. The company's own \"data moat\" claim is plausible but unquantified — ask how many labelled clinical interactions exist and who owns the labels.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Inc42 and Digital Health News", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "C.3.b": {
      band: "Fair",
      reasoning: "There is no genuine network effect here. Low CAC comes from sponsor-funded distribution, not from users making the product better for other users. The family repeat-usage loop is one-sided and local, which is the Fair anchor. The Poor anchor (\"growth is bought\") does not fit because growth is not bought — it is channelled.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Inc42 and Digital Health News", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "C.5": {
      measured: { value: -239, unit: "bps" },
      reasoning: "-239 bps on CM1, or -865 bps on the deck's gross-margin definition. Poor on either. Margin fell while revenue grew 83% because the mix moved to lower-margin corporate work — ARPU per life more than halved. The plan then assumes uninterrupted margin expansion every year to FY33 with no stated mechanism. This is the single biggest forecast question.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Poor (3.0) band holds, rather than moving to Fair (5.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
    },
    "C.6": {
      measured: { value: 40.8, unit: "%" },
      reasoning: "40.8% — Excellent band (Series A cut 45%), but this is a BOUNDED ESTIMATE, not an actual. No client-level revenue table exists in the model. The build deliberately takes the most concentrated reading of every channel: the whole domestic-insurance line as one insurer, the whole pharma line as one partner, the whole B2B2C line as one account, plus the two largest corporates at 2.5x and 2.0x the average corporate account. On a looser reading it is c.35%. The conclusion is therefore robust to the assumption — concentration is not severe — but the score is close to the band edge and must be replaced with the actual top-ten table. The teaser's Corp 1–10 table was deliberately NOT used: those accounts carry 1.0k–4.0k lives against a c.4.1k average, so it is an adoption-rate sample and would have flattered the answer.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "C.8": {
      band: "Fair",
      reasoning: "Fair. Policy direction is a clear and well-documented tailwind — the teaser sets out IRDAI's \"Insurance for All by 2047\" (2022), the National Health Claims Exchange (2023), the Bima Trinity of Bima Sugam, Vistaar and Vahak (2024), and 100% insurance FDI with composite licences under the new Insurance Bill (2025), alongside Ayushman Bharat Digital Mission and ABHA interoperability which our external sources cite as the primary driver of Indian digital health growth. Zyla is also not itself a licensed entity: it does not underwrite, dispense or operate a hospital, so it captures the tailwind without carrying the licensing burden, and it holds SOC 2 and ISO 27001. BUT IT IS NOT GOOD, FOR TWO REASONS. It employs doctors delivering remote clinical advice, which brings it inside the Telemedicine Practice Guidelines; and it processes sensitive personal health data at very large scale (2L+ paid lives) under a DPDP Act regime whose operating rules are still bedding in. A licensed-adjacent sector with periodic compliance obligations and a known change in the pipeline whose impact is not yet clear is precisely the Fair anchor. ASK: the DPDP compliance assessment and consent architecture; medical-council registration status of the clinical team; the SOC 2 report and ISO 27001 certificate with dates; and the data-processing agreements with insurer clients and the liability they carry. Supporting evidence recorded at Evidence & Workings row 72.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Grand View Research (ABDM as growth driver)", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "D.1": {
      band: "Excellent",
      reasoning: "1.60x against the last priced round — Excellent band (ideal 1.5x–3.0x). But 6.0x against the ₹10 Cr the balance sheet shows was raised in FY26, which would be Poor. The FY26 infusion is undocumented. Ask what it was, from whom and at what price; the answer swings this parameter by four score points.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Exfinity Venture Partners — investor's own media page", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "D.2": {
      band: "Poor",
      reasoning: "182.9% — Poor. The ask is nearly twice all the equity ever taken in. On the external estimate of total capital raised (c.₹51 Cr) it would be 115% and score Fair. The ₹18 Cr difference between the balance sheet and the external funding record needs reconciling.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Poor (3.0) band holds, rather than moving to Fair (5.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Entrepreneur India — \"Zyla Health Raises Series A Funding To Accelerate Growth\"", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Poor (3.0) band holds, rather than moving to Fair (5.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "D.3": {
      measured: { value: 50, unit: "%" },
      reasoning: "INFERENCE — MUST BE CONFIRMED. ₹30 Cr of ₹60 Cr is 50%, which is Excellent (Series A cut 40%). But the deck says \"committed / closed\" without saying by whom. If that ₹30 Cr is existing investors following on, the Excellent score is right and it is a strong conviction signal. If it is new money, this parameter is not evidenced at all and should be blanked. Get the commitment letters and the investor names before this score is relied on.",
      diligenceAsk: "Already at the top band on current evidence. Confirm the following in due diligence so the rating holds: INFERENCE — MUST BE CONFIRMED.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      flag: {
        kind: "inferred",
        summary: "₹30 Cr of the ₹60 Cr ask is treated as existing-investor money. The deck does not say who committed it.",
      },
      citations: [
        { source: "M. Cover_Zyla Health", quote: "Already at the top band on current evidence. Confirm the following in due diligence so the rating holds: INFERENCE — MUST BE CONFIRMED.", type: "Company document", tier: "2" },
      ],
    },
    "D.4": {
      measured: { value: -41.2, unit: "%" },
      reasoning: "-41.2% — a discount to the peer median, so Excellent (lower is better). Read this with care: all four comps are 2021–23 rounds struck before the healthtech re-rating, so 21.8x is very likely generous and the true discount is smaller. Also unresolved: whether ₹350 Cr is pre- or post-money (post-money would give 10.6x and a wider discount), and whether the raise is ₹60 Cr or the ₹50 Cr the same sheet shows.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Inc42 and BW Disrupt", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "D.7": {
      measured: { value: 98.9, unit: "%" },
      reasoning: "98.9% — Excellent (cut 80%). All three stated uses are growth and only ₹0.67 Cr goes to debt. Caveat: cash was nil at FY26 year end, so economically part of the round will plug working capital whatever the stated intent. This is the stated use, not the economic use.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "M. Cover_Zyla Health", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "D.8": {
      band: "Fair",
      reasoning: "The story is genuinely good — specific, costed and partly executed, which on its own would be Good or better. But the Qualitative Anchors instruction for this parameter is explicit: short runway caps it at Fair however good the story, and cross-checking against B.7 shows nil months of liquid runway. Capped at Fair accordingly. If the ₹17.89 Cr investments balance proves liquid, runway is c.19.7 months and this should be revisited to Good.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "hrnxt.com, reporting ETtech", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "E.1": {
      band: "Excellent",
      reasoning: "Excellent band (cut US$10 Bn). Corroborated in scale by three further independent reports (IMARC US$16.1 Bn 2024, 6Wresearch US$11.2 Bn 2024, MRFR US$8.1 Bn 2024). The 2024 base is used rather than a forecast year, which is the conservative choice.",
      diligenceAsk: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Grand View Research — India Digital Health Market Report", quote: "Already at the top band (Excellent, 9.0) on current evidence — confirm no material facts remain undisclosed during due diligence.", type: "Company document", tier: "2" },
      ],
    },
    "E.4": {
      measured: { value: 7.5, unit: "Years" },
      reasoning: "7.5 years average, Good band (Excellent cut 8). Two of the three peers are well-established; the average is pulled down by PB Health, which is only 18 months old but is by far the best capitalised. Zyla at 9 years is older than the peer average.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Business Standard", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "E.5": {
      measured: { value: 22, unit: "Months" },
      reasoning: "22 months average, Fair band (cuts 9 / 18 / 30). BeatO's 44-month drought is the signal here: the best-funded pure-play chronic-care company in India has not raised since Nov-2022.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Business Standard", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "E.7.a": {
      measured: { value: 1, unit: "Count" },
      reasoning: "One distinct positive named-peer capital event in the twelve months to Jul-2026 — the PB Health / Fitterfly acquisition. Fair band (cuts 5 / 3 / 1). The window was widened from six to twelve months (Assumption B.8) because a strict Feb–Jul 2026 window returned zero evidenced peer events; on that strict basis the score would have been Poor. The thinness is itself the finding.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Inc42 and BW Disrupt", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Fair (5.0) band holds, rather than moving to Good (7.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "E.7.b": {
      measured: { value: 2, unit: "x" },
      reasoning: "Four positive to two negative events, a ratio of 2.0 — Good band (cuts 3.0 / 1.5 / 0.8). Deliberately not scored Excellent: the structural story is intact but Indian healthtech is being crowded out of the capital allocation by AI and fintech, and that is a real headwind for this raise.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Entrackr", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "F.1": {
      measured: { value: 5, unit: "US$ Bn" },
      reasoning: "US$5.0 Bn, Good band (Excellent cut US$10 Bn). Derived, because no India-specific digital chronic-care TAM is published. The 45% share is the weakest assumption in the assessment, but the top-down cross-check (US$8.3 Bn) lands in the same band so the score is not sensitive to it.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Fortune Business Insights — Digital Health Market", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "F.4": {
      measured: { value: 7.5, unit: "Years" },
      reasoning: "7.5 years, Good band. The peer set is common to E.4 and F.4 because the deal database resolves both Zyla's sector and its clubbed sub-sector to \"Healthtech\". All three peers — PB Health, Fitterfly, BeatO — are chronic-care players, so the set is if anything a better fit for the sub-sector than the sector.",
      diligenceAsk: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Business Standard", quote: "No specific evidence gap is called out in the current material for this parameter. Independently verify the underlying evidence in due diligence to confirm the Good (7.0) band holds, rather than moving to Excellent (9.0) or being revised downward.", type: "Company document", tier: "2" },
      ],
    },
    "F.5": {
      measured: { value: 22, unit: "Months" },
      reasoning: "22 months, Fair band. See the note at E.5 — BeatO's 44-month gap without a raise is the material signal for this sub-sector.",
      diligenceAsk: "Confirm the gap noted in diligence — See the note at E.5 — BeatO's 44-month gap without a raise is the material signal for this sub-sector. — to verify whether this parameter should move from Fair (5.0) to Good (7.0).",
      evidenceTier: "Verified",
      confidence: "high",
      asOf: "August 2026",
      citations: [
        { source: "Business Standard", quote: "Confirm the gap noted in diligence — See the note at E.5 — BeatO's 44-month gap without a raise is the material signal for this sub-sector. — to verify whether this parameter should move from Fair (5.0) to Good (7.0).", type: "Company document", tier: "2" },
      ],
    },
  },
}
