/**
 * Mock Database for Investor Discovery (Stage 3).
 *
 * This file contains the complete mock dataset that mirrors the exact
 * API contract the backend will eventually provide. When real APIs are
 * ready, only the fetch layer needs to change — the UI components
 * consume this shape directly.
 *
 * Data structure follows screens_and_functionality.md Section 10.
 */

// ── Snapshot context (from Stage 1 + 2) ──────────────────────
export const snapshotData = {
  evaluationScore: 6.8,
  maxScore: 10,
  scoreBand: 'Average',
  stage: 'Series A',
  sector: 'HealthTech',
  raiseAmount: '₹50 – ₹80 Cr',
};

// ── KPI summary ──────────────────────────────────────────────
export const kpiData = {
  masterRecords: 7754,
  topMatches: 45,
  avgMatchScore: 91,
  savedForOutreach: 0,  // starts at 0, updates as user saves
};

// ── Filter universe (options + AI pre-filled defaults) ───────
export const filterOptions = {
  stages: ['Seed', 'Pre-Series A', 'Series A', 'Series B', 'Series C', 'Growth'],
  raiseSizes: ['< ₹10 Cr', '₹10 – ₹30 Cr', '₹30 – ₹50 Cr', '₹50 – ₹80 Cr', '₹80 – ₹150 Cr', '₹150 Cr+'],
  sectors: ['HealthTech', 'FinTech', 'Enterprise SaaS', 'EdTech', 'Consumer', 'DeepTech', 'AgriTech', 'CleanTech'],
  countries: ['India', 'US', 'Singapore', 'UK', 'UAE', 'Japan', 'Global'],
  expansionFocus: ['SEA', 'US', 'Europe', 'Middle East', 'Japan', 'Global'],
  investorTypes: ['Angel & UHNI', 'Micro VC & Accelerators', 'Family Office', 'Domestic VC', 'Global VC', 'Corporate VC', 'Domestic PE', 'Global PE', 'Others'],
};

export const filterDefaults = {
  stage: 'Series A',
  raiseSize: '₹50 – ₹80 Cr',
  sector: 'HealthTech',
  country: 'India',
  expansionFocus: 'SEA',
  investorType: '',
};

// ── The Investor Master List ─────────────────────────────────
// Each object represents a single investor entity with all the
// data needed for the table, drawer, and filtering logic.

export const investorDatabase = [
  {
    id: 'inv-001',
    name: 'Accel',
    logoInitial: 'A',
    logoColor: '#000000',
    rating: 5,
    matchScore: 95,
    tier: 'top',
    investorType: 'Growth VC',
    avgTicket: '$15M – $30M',
    sectorFocus: ['Enterprise SaaS', 'HealthTech'],
    geography: ['India', 'SEA'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'Enterprise SaaS', score: 100 },
      { dimension: 'Ticket Size', detail: '$15M-$30M', score: 92 },
      { dimension: 'Stage', detail: 'Series B', score: 100 },
    ],
    contact: {
      name: 'Prashant Gupta',
      initials: 'PG',
      title: 'Partner',
      location: 'Bangalore',
      email: 'prashant.gupta@accel.com',
    },
    aiRationale: 'Backed Freshworks, Chargebee, BrowserStack. Sweeps $10-30M ticket checks directly into Series B enterprise SaaS rounds. Active thesis in India HealthTech since 2023.',
    portfolioTags: [
      { name: 'Freshworks', color: '#05A86B' },
      { name: 'Chargebee', color: '#FF6B35' },
      { name: 'BrowserStack', color: '#2563eb' },
    ],
    recentDeals: [
      { company: 'Observe.AI', round: 'Series B', amount: '$22M' },
      { company: 'Innovaccer', round: 'Series F', amount: '$150M' },
    ],
    stats: { deals12M: 16, medianTicket: '$18M', leadPct: 74, exits: 6 },
  },
  {
    id: 'inv-002',
    name: 'Peak XV Partners',
    logoInitial: 'P',
    logoColor: '#e91e63',
    rating: 5,
    matchScore: 93,
    tier: 'top',
    investorType: 'Growth VC',
    avgTicket: '$10M – $25M',
    sectorFocus: ['FinTech', 'HealthTech'],
    geography: ['India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 100 },
      { dimension: 'Ticket Size', detail: '$10M-$25M', score: 88 },
      { dimension: 'Stage', detail: 'Series A-B', score: 95 },
    ],
    contact: {
      name: 'Rajan Anandan',
      initials: 'RA',
      title: 'Managing Director',
      location: 'Mumbai',
      email: 'rajan@peakxv.com',
    },
    aiRationale: 'Former Sequoia India. Deep HealthTech portfolio including Practo, PharmEasy. Consistently leads Series A/B rounds in $10-25M range for Indian SaaS and health companies.',
    portfolioTags: [
      { name: 'Practo', color: '#0066cc' },
      { name: 'PharmEasy', color: '#16a34a' },
    ],
    recentDeals: [
      { company: 'Pristyn Care', round: 'Series E', amount: '$96M' },
      { company: 'Curefit', round: 'Series D', amount: '$75M' },
    ],
    stats: { deals12M: 22, medianTicket: '$14M', leadPct: 68, exits: 9 },
  },
  {
    id: 'inv-003',
    name: 'Lightspeed India',
    logoInitial: 'L',
    logoColor: '#22c55e',
    rating: 4,
    matchScore: 91,
    tier: 'top',
    investorType: 'Growth VC',
    avgTicket: '$20M+',
    sectorFocus: ['Consumer', 'Enterprise SaaS'],
    geography: ['Global'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'SaaS overlap', score: 85 },
      { dimension: 'Ticket Size', detail: '$20M+', score: 90 },
      { dimension: 'Stage', detail: 'Series B+', score: 100 },
    ],
    contact: {
      name: 'Dev Khare',
      initials: 'DK',
      title: 'Partner',
      location: 'Bangalore',
      email: 'dev@lsvp.com',
    },
    aiRationale: 'Strong Enterprise SaaS conviction. Backed Darwinbox (HR SaaS unicorn), has active healthcare adjacency thesis. $20M+ cheque size aligns well with target raise.',
    portfolioTags: [
      { name: 'Darwinbox', color: '#7c3aed' },
      { name: 'Yellow.ai', color: '#f59e0b' },
    ],
    recentDeals: [
      { company: 'Darwinbox', round: 'Series D', amount: '$72M' },
      { company: 'Yellow.ai', round: 'Series C', amount: '$78M' },
    ],
    stats: { deals12M: 12, medianTicket: '$24M', leadPct: 82, exits: 4 },
  },
  {
    id: 'inv-004',
    name: 'Matrix Partners India',
    logoInitial: 'M',
    logoColor: '#1d4ed8',
    rating: 5,
    matchScore: 89,
    tier: 'top',
    investorType: 'Domestic VC',
    avgTicket: '$8M – $20M',
    sectorFocus: ['HealthTech', 'FinTech', 'Enterprise SaaS'],
    geography: ['India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 100 },
      { dimension: 'Ticket Size', detail: '$8M-$20M', score: 78 },
      { dimension: 'Stage', detail: 'Series A-B', score: 95 },
    ],
    contact: {
      name: 'Sudipto Sannigrahi',
      initials: 'SS',
      title: 'Principal',
      location: 'Bangalore',
      email: 'sudipto@matrixpartners.in',
    },
    aiRationale: 'Led Razorpay, Country Delight, Ola. Strong presence in Indian enterprise and consumer health rounds. Actively seeking HealthTech Series A/B deals in ₹50-100Cr range.',
    portfolioTags: [
      { name: 'Razorpay', color: '#2563eb' },
      { name: 'Country Delight', color: '#16a34a' },
      { name: 'Ola', color: '#0f172a' },
    ],
    recentDeals: [
      { company: 'Razorpay', round: 'Series F', amount: '$375M' },
      { company: 'Mosaic Wellness', round: 'Series B', amount: '$24M' },
    ],
    stats: { deals12M: 14, medianTicket: '$12M', leadPct: 71, exits: 7 },
  },
  {
    id: 'inv-005',
    name: 'Nexus Venture Partners',
    logoInitial: 'N',
    logoColor: '#7c3aed',
    rating: 4,
    matchScore: 88,
    tier: 'top',
    investorType: 'Domestic VC',
    avgTicket: '$10M – $25M',
    sectorFocus: ['Enterprise SaaS', 'DeepTech'],
    geography: ['India', 'US'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'Enterprise SaaS', score: 92 },
      { dimension: 'Ticket Size', detail: '$10M-$25M', score: 85 },
      { dimension: 'Stage', detail: 'Series A-B', score: 90 },
    ],
    contact: {
      name: 'Jishnu Bhattacharjee',
      initials: 'JB',
      title: 'Managing Director',
      location: 'Bangalore',
      email: 'jishnu@nexusvp.com',
    },
    aiRationale: 'Backed Postman, Unacademy, Delhivery at early stages. Enterprise SaaS is core thesis. Cross-border India-US portfolio provides distribution advantage.',
    portfolioTags: [
      { name: 'Postman', color: '#ff6c37' },
      { name: 'Delhivery', color: '#dc2626' },
    ],
    recentDeals: [
      { company: 'Postman', round: 'Series D', amount: '$225M' },
      { company: 'Turbo', round: 'Series A', amount: '$18M' },
    ],
    stats: { deals12M: 10, medianTicket: '$16M', leadPct: 65, exits: 5 },
  },
  {
    id: 'inv-006',
    name: 'Elevation Capital',
    logoInitial: 'E',
    logoColor: '#0891b2',
    rating: 4,
    matchScore: 86,
    tier: 'top',
    investorType: 'Growth VC',
    avgTicket: '$15M – $40M',
    sectorFocus: ['FinTech', 'Consumer', 'Enterprise SaaS'],
    geography: ['India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'SaaS adjacency', score: 78 },
      { dimension: 'Ticket Size', detail: '$15M-$40M', score: 95 },
      { dimension: 'Stage', detail: 'Series B+', score: 90 },
    ],
    contact: {
      name: 'Mukul Arora',
      initials: 'MA',
      title: 'Partner',
      location: 'Gurgaon',
      email: 'mukul@elevationcapital.com',
    },
    aiRationale: 'Formerly SAIF Partners. Backed Meesho, ShareChat, Unacademy. Growing HealthTech interest with recent bets in digital health. Cheque size perfectly aligned.',
    portfolioTags: [
      { name: 'Meesho', color: '#e91e63' },
      { name: 'ShareChat', color: '#2196f3' },
    ],
    recentDeals: [
      { company: 'Meesho', round: 'Series F', amount: '$275M' },
      { company: 'Xpressbees', round: 'Series F', amount: '$80M' },
    ],
    stats: { deals12M: 18, medianTicket: '$22M', leadPct: 55, exits: 8 },
  },
  {
    id: 'inv-007',
    name: 'Chiratae Ventures',
    logoInitial: 'C',
    logoColor: '#dc2626',
    rating: 4,
    matchScore: 84,
    tier: 'good',
    investorType: 'Domestic VC',
    avgTicket: '$5M – $15M',
    sectorFocus: ['HealthTech', 'AgriTech', 'Enterprise SaaS'],
    geography: ['India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 100 },
      { dimension: 'Ticket Size', detail: '$5M-$15M', score: 65 },
      { dimension: 'Stage', detail: 'Series A', score: 100 },
    ],
    contact: {
      name: 'Sudhir Sethi',
      initials: 'SS',
      title: 'Founder & Chairman',
      location: 'Bangalore',
      email: 'sudhir@chiratae.com',
    },
    aiRationale: 'One of India\'s oldest VC firms with deep HealthTech expertise. Backed Lenskart, Myntra at early stages. Smaller cheque but strong syndication and co-investment network.',
    portfolioTags: [
      { name: 'Lenskart', color: '#0f172a' },
      { name: 'Myntra', color: '#e91e63' },
    ],
    recentDeals: [
      { company: 'Cloudnine', round: 'Series C', amount: '$30M' },
      { company: 'mFine', round: 'Series B', amount: '$16M' },
    ],
    stats: { deals12M: 8, medianTicket: '$8M', leadPct: 45, exits: 12 },
  },
  {
    id: 'inv-008',
    name: 'Temasek',
    logoInitial: 'T',
    logoColor: '#0f766e',
    rating: 5,
    matchScore: 82,
    tier: 'good',
    investorType: 'Global PE',
    avgTicket: '$50M+',
    sectorFocus: ['HealthTech', 'FinTech', 'CleanTech'],
    geography: ['Global', 'Singapore', 'India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 100 },
      { dimension: 'Ticket Size', detail: '$50M+', score: 45 },
      { dimension: 'Stage', detail: 'Series B+', score: 80 },
    ],
    contact: {
      name: 'Rohit Sipahimalani',
      initials: 'RS',
      title: 'CIO',
      location: 'Singapore',
      email: 'rohit@temasek.com.sg',
    },
    aiRationale: 'Sovereign wealth fund with massive India HealthTech exposure. Backed Manipal Health, PharmEasy. Typically co-invests in rounds and can serve as a follow-on anchor for Series C.',
    portfolioTags: [
      { name: 'PharmEasy', color: '#16a34a' },
      { name: 'Manipal Health', color: '#0891b2' },
    ],
    recentDeals: [
      { company: 'PharmEasy', round: 'Series E', amount: '$350M' },
      { company: 'Manipal Health', round: 'Late Stage', amount: '$200M' },
    ],
    stats: { deals12M: 28, medianTicket: '$65M', leadPct: 30, exits: 15 },
  },
  {
    id: 'inv-009',
    name: 'Blume Ventures',
    logoInitial: 'B',
    logoColor: '#f97316',
    rating: 4,
    matchScore: 80,
    tier: 'good',
    investorType: 'Micro VC & Accelerators',
    avgTicket: '$2M – $8M',
    sectorFocus: ['HealthTech', 'DeepTech', 'Consumer'],
    geography: ['India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 100 },
      { dimension: 'Ticket Size', detail: '$2M-$8M', score: 42 },
      { dimension: 'Stage', detail: 'Seed to Series A', score: 85 },
    ],
    contact: {
      name: 'Karthik Reddy',
      initials: 'KR',
      title: 'Co-Founder & Managing Partner',
      location: 'Mumbai',
      email: 'karthik@blume.vc',
    },
    aiRationale: 'Prolific early-stage investor with HealthTech conviction. Backed Purplle, Unacademy early. Could participate as a smaller co-investor or syndicate partner alongside a lead.',
    portfolioTags: [
      { name: 'Purplle', color: '#9333ea' },
      { name: 'Unacademy', color: '#16a34a' },
    ],
    recentDeals: [
      { company: 'Purplle', round: 'Series D', amount: '$33M' },
      { company: 'Zetwerk', round: 'Series F', amount: '$120M' },
    ],
    stats: { deals12M: 20, medianTicket: '$5M', leadPct: 38, exits: 10 },
  },
  {
    id: 'inv-010',
    name: 'Warburg Pincus',
    logoInitial: 'W',
    logoColor: '#1e3a5f',
    rating: 5,
    matchScore: 78,
    tier: 'good',
    investorType: 'Global PE',
    avgTicket: '$100M+',
    sectorFocus: ['HealthTech', 'FinTech'],
    geography: ['Global', 'India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 100 },
      { dimension: 'Ticket Size', detail: '$100M+', score: 30 },
      { dimension: 'Stage', detail: 'Growth/Late', score: 65 },
    ],
    contact: {
      name: 'Vishal Mahadevia',
      initials: 'VM',
      title: 'Managing Director',
      location: 'Mumbai',
      email: 'vishal@warburgpincus.com',
    },
    aiRationale: 'Major PE investor in Indian healthcare — owns Lenskart, backed Thyrocare. Too large for lead but could anchor a future Series C+ round as portfolio matures.',
    portfolioTags: [
      { name: 'Lenskart', color: '#0f172a' },
      { name: 'Thyrocare', color: '#dc2626' },
    ],
    recentDeals: [
      { company: 'Lenskart', round: 'Late Stage', amount: '$500M' },
      { company: 'Bikaji Foods', round: 'Pre-IPO', amount: '$120M' },
    ],
    stats: { deals12M: 8, medianTicket: '$150M', leadPct: 60, exits: 18 },
  },
  {
    id: 'inv-011',
    name: 'Sony Innovation Fund',
    logoInitial: 'S',
    logoColor: '#1e40af',
    rating: 3,
    matchScore: 76,
    tier: 'good',
    investorType: 'Corporate VC',
    avgTicket: '$3M – $10M',
    sectorFocus: ['HealthTech', 'DeepTech', 'Consumer'],
    geography: ['Japan', 'India', 'Global'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 85 },
      { dimension: 'Ticket Size', detail: '$3M-$10M', score: 55 },
      { dimension: 'Stage', detail: 'Series A-B', score: 90 },
    ],
    contact: {
      name: 'Gen Tsuchikawa',
      initials: 'GT',
      title: 'Head of Investments',
      location: 'Tokyo',
      email: 'gen.t@sony.com',
    },
    aiRationale: 'Existing investor from prior round. Strategic CVC with healthcare device and AI convergence thesis. Can provide Japan market distribution and technology co-dev partnerships.',
    portfolioTags: [
      { name: 'Acko', color: '#0891b2' },
      { name: 'Merilytics', color: '#7c3aed' },
    ],
    recentDeals: [
      { company: 'Acko', round: 'Series D', amount: '$60M' },
      { company: 'Merilytics', round: 'Series B', amount: '$25M' },
    ],
    stats: { deals12M: 6, medianTicket: '$6M', leadPct: 15, exits: 2 },
  },
  {
    id: 'inv-012',
    name: 'Healthquad',
    logoInitial: 'H',
    logoColor: '#059669',
    rating: 4,
    matchScore: 92,
    tier: 'top',
    investorType: 'Domestic VC',
    avgTicket: '$5M – $15M',
    sectorFocus: ['HealthTech'],
    geography: ['India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 100 },
      { dimension: 'Ticket Size', detail: '$5M-$15M', score: 70 },
      { dimension: 'Stage', detail: 'Series A-B', score: 100 },
    ],
    contact: {
      name: 'Savneet Singh',
      initials: 'SvS',
      title: 'Managing Partner',
      location: 'Delhi',
      email: 'savneet@healthquad.in',
    },
    aiRationale: 'India\'s only pure-play healthcare VC fund. Portfolio includes Meddo, CallHealth, MedCords. Deep domain network across hospitals, pharma, and diagnostics. Ideal sector-specialist co-lead.',
    portfolioTags: [
      { name: 'Meddo', color: '#0891b2' },
      { name: 'CallHealth', color: '#16a34a' },
      { name: 'MedCords', color: '#7c3aed' },
    ],
    recentDeals: [
      { company: 'Meddo', round: 'Series A', amount: '$8M' },
      { company: 'Phable', round: 'Series A', amount: '$6M' },
    ],
    stats: { deals12M: 5, medianTicket: '$7M', leadPct: 80, exits: 3 },
  },
  {
    id: 'inv-013',
    name: 'Tiger Global',
    logoInitial: 'T',
    logoColor: '#ea580c',
    rating: 5,
    matchScore: 85,
    tier: 'top',
    investorType: 'Global VC',
    avgTicket: '$25M – $100M',
    sectorFocus: ['Enterprise SaaS', 'FinTech', 'Consumer'],
    geography: ['Global'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'SaaS adjacency', score: 75 },
      { dimension: 'Ticket Size', detail: '$25M-$100M', score: 80 },
      { dimension: 'Stage', detail: 'Series B+', score: 100 },
    ],
    contact: {
      name: 'Scott Shleifer',
      initials: 'SS',
      title: 'Partner',
      location: 'New York',
      email: 'scott@tigerglobal.com',
    },
    aiRationale: 'World\'s most prolific tech investor. Backed Flipkart, Razorpay at scale. Known for speed and non-dilutive governance. Large cheque may require Series B+ timing.',
    portfolioTags: [
      { name: 'Flipkart', color: '#2563eb' },
      { name: 'Razorpay', color: '#0f172a' },
    ],
    recentDeals: [
      { company: 'Razorpay', round: 'Series F', amount: '$375M' },
      { company: 'Slice', round: 'Series B', amount: '$220M' },
    ],
    stats: { deals12M: 35, medianTicket: '$45M', leadPct: 42, exits: 22 },
  },
  {
    id: 'inv-014',
    name: 'Kalaari Capital',
    logoInitial: 'K',
    logoColor: '#be185d',
    rating: 4,
    matchScore: 83,
    tier: 'good',
    investorType: 'Domestic VC',
    avgTicket: '$5M – $20M',
    sectorFocus: ['HealthTech', 'EdTech', 'Consumer'],
    geography: ['India'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 90 },
      { dimension: 'Ticket Size', detail: '$5M-$20M', score: 72 },
      { dimension: 'Stage', detail: 'Series A-B', score: 95 },
    ],
    contact: {
      name: 'Vani Kola',
      initials: 'VK',
      title: 'Founder & Managing Director',
      location: 'Bangalore',
      email: 'vani@kalaari.com',
    },
    aiRationale: 'Backed Dream11, Cure.fit, Myntra early. Strong founder network in Indian HealthTech ecosystem. Known for hands-on support during scaling phase.',
    portfolioTags: [
      { name: 'Dream11', color: '#dc2626' },
      { name: 'Cure.fit', color: '#059669' },
    ],
    recentDeals: [
      { company: 'Cure.fit', round: 'Series D', amount: '$75M' },
      { company: 'Cred', round: 'Series E', amount: '$80M' },
    ],
    stats: { deals12M: 11, medianTicket: '$10M', leadPct: 58, exits: 8 },
  },
  {
    id: 'inv-015',
    name: 'GIC (Singapore)',
    logoInitial: 'G',
    logoColor: '#475569',
    rating: 5,
    matchScore: 74,
    tier: 'good',
    investorType: 'Global PE',
    avgTicket: '$75M+',
    sectorFocus: ['HealthTech', 'FinTech', 'CleanTech'],
    geography: ['Global', 'Singapore'],
    isSaved: false,
    matchBreakdown: [
      { dimension: 'Sector', detail: 'HealthTech', score: 85 },
      { dimension: 'Ticket Size', detail: '$75M+', score: 25 },
      { dimension: 'Stage', detail: 'Growth/Late', score: 55 },
    ],
    contact: {
      name: 'Lee Kok Sun',
      initials: 'LK',
      title: 'Chief Investment Officer',
      location: 'Singapore',
      email: 'koksun@gic.com.sg',
    },
    aiRationale: 'Singapore sovereign fund. Massive India healthcare bets including BYJU\'s, Swiggy. Too large for current round but excellent relationship for Series C+ anchor investor.',
    portfolioTags: [
      { name: 'Swiggy', color: '#ea580c' },
      { name: 'Zomato', color: '#dc2626' },
    ],
    recentDeals: [
      { company: 'Swiggy', round: 'IPO anchor', amount: '$400M' },
      { company: 'ReNew Power', round: 'Growth', amount: '$300M' },
    ],
    stats: { deals12M: 15, medianTicket: '$120M', leadPct: 25, exits: 10 },
  },
];
